### PR TITLE
Updated mavencentral source url

### PR DESCRIPTION
**Pull request by disulliv**
Before (broken): http://central.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2/11/2.11.1/jackson-module-scala_2.11-2.11.1-sources.jar

After (not broken): https://search.maven.org/remotecontent?filepath=com/fasterxml/jackson/module/jackson-module-scala_2.11/2.11.1/jackson-module-scala_2.11-2.11.1-sources.jar

RE: [issue 707](https://github.com/clearlydefined/service/issues/707)

### CODE REVIEW

**Comment by jeffmendoza** [comment]
#707

**Comment by jeffmendoza** [comment]
@disulliv Running in dev now, can you harvest a new maven package and verify the definition has the new url? https://dev.clearlydefined.io/
https://clearlydefined.visualstudio.com/ClearlyDefined/_release

**Comment by disulliv** [comment]
New URL is showing up here: https://dev.clearlydefined.io/definitions/maven/mavencentral/org.assertj/assertj-core/3.16.1

**Comment by jeffmendoza** [comment]
```yaml
  sourceLocation:
    name: assertj-core
    namespace: org.assertj
    provider: mavencentral
    revision: 3.16.1
    type: sourcearchive
    url: >-
      https://search.maven.org/remotecontent?filepath=org/assertj/assertj-core/3.16.1/assertj-core-3.16.1-sources.jar
```
Looks good! I'll push to prod and close #707 

> but definitions > urls are not updated. Maybe another work item for that?

Yes, please create another issue for that. Thanks!

**Pull request merged**
