### PR TITLE
Fixed incorrect continuation token when searching with sort

### PR DESCRIPTION
**Pull request by qtomlinson**
The continuation token was generated based on _mongo.partitionKey. This is correct when _mongo.partitionKey is the only sort field.  When there are other sort fields in the query, the sequence of records are influenced by those fields. Continuation token based on only _mongo.partitionKey value does not produce the correct results for next pages.

There is a npm package on "cursor based pagination": https://www.npmjs.com/package/mongo-cursor-pagination The library supports one "paginatedField".  The ClearlyDefined api supports sort resulting in multiple sort fields. For example: sort on namespace sorts on three fields: ['coordinates.namespace', 'coordinates.name', 'coordinates.revision'].  So the library is not sufficient for CD's need.

To generate the correct next page, the continuation token needs to record all the values for sort fields. As an extension of existing logic, _mongo.partitionKey will always be included to the sort fields as a tie breaker. Also added logic to generate pagination query based on multiple sort values.

Task: https://github.com/clearlydefined/service/issues/670

### CODE REVIEW

**Comment by qtomlinson** [comment]
@mpcen ready for review

**Review by mpcen — APPROVED** [review]

**Comment by qtomlinson** [comment]
@mpcen This commit is for correctness only.  There may be a performance impact which may be addressed by adding combination indexes (e.g. described.releaseDate + _mongo.partitionKey) to the definition DB.

**Comment by mpcen** [comment]
@qtomlinson i think the perf hit is fine as we're starting a push for perf improvements now.

**Comment by qtomlinson** [comment]
@mpcen rebased and ready.

**Pull request merged**
