### PR TITLE
Removing links that no longer point to EULA

### PR DESCRIPTION
**Pull request by capfei**
Both now point to MIT

### CODE REVIEW

**Comment by capfei** [comment]
Fixes #746

**Comment by jeffmendoza** [comment]
@capfei This is now running on https://dev.clearlydefined.io/ Is there a component that could be harvested there that would show the change ?

**Comment by capfei** [comment]
@jeffmendoza I just started a harvest for [Microsoft.Azure.Cosmos@3.2.0](https://dev.clearlydefined.io/?sortDesc=true&sort=releaseDate&name=Microsoft.Azure.Cosmos).

**Comment by capfei** [comment]
@jeffmendoza It stills shows `OTHER`. Did my harvest request fail?

**Comment by jeffmendoza** [comment]
Looks like the harvest failed, only "partially harvested" I'll check the logs

**Comment by jeffmendoza** [comment]
@capfei Looks like harvesting worked this time. It is showing up as NOASSERTION instead of OTHER. Is this correct?

**Pull request merged**
