### PR TITLE
Add support for Gradle Plugin Repository in service

### PR DESCRIPTION
**Pull request by qtomlinson**
Task: https://github.com/clearlydefined/service/issues/882

### CODE REVIEW

**Comment by qtomlinson** [comment]
@nellshamrell service part of the gradle plugin repository support

**Review by nellshamrell — COMMENTED** [review]
This is looking great! Going to do some testing in my local environment before merging, but this looks fantastic!

**Comment by nellshamrell** [comment]
@qtomlinson Do you mind doing one more pull request to our documentation repo? Specifically, adding gradle under "Maven" on [this page](https://github.com/clearlydefined/clearlydefined/blob/master/docs/adding-sources.md)

**Comment by qtomlinson** [comment]
@nellshamrell Thanks for the suggestion and pointer!  [Pull request](https://github.com/clearlydefined/clearlydefined/pull/153) is ready.

**Pull request merged**
