### PR TITLE
Added Unit Test for application startup

### LINKED ISSUE #595: Cover app.js with a few tests to prevent basic regressions
### Given:
- it's convenient to modify parts of the program independently, covering their intended behavior with tests
- unit tests currently do not apply to the startup phase of running the service -as exemplified by PR #590 introducing an error preventing it from start
- expanding test coverage is an implicit goal

### Goals:
- keep the convenience
- protect us from changes that break the service initial phase

## Proposal
Cover app.js createApp phase with at least a basic test, that will fail when setup is not possible.

### PR DESCRIPTION
**Pull request by ignacionr**
Redone test, simplified.
This closes #595

### CODE REVIEW

**Comment by geneh** [comment]
The test has failed:
```
nyc mocha "test/**/*.js" && eslint .

ajv-errors: Ajv option jsonPointers changed to true
/home/vsts/work/1/s/node_modules/@octokit/rest/lib/plugins/authentication/authenticate.js:25
        throw new Error('Token authentication requires a token to be set')
        ^

Error: Token authentication requires a token to be set
    at authenticate (/home/vsts/work/1/s/node_modules/@octokit/rest/lib/plugins/authentication/authenticate.js:25:15)
    at Object.getClient (/home/vsts/work/1/s/lib/github.js:3:280)
    at new GitHubCurationService (/home/vsts/work/1/s/providers/curation/github.js:7:469)
    at module.exports (/home/vsts/work/1/s/providers/curation/github.js:78:472)
    at Object.github [as service] (/home/vsts/work/1/s/providers/curation/githubConfig.js:3:708)
    at createApp (/home/vsts/work/1/s/app.js:3:2799)
    at Object.<anonymous> (/home/vsts/work/1/s/test/app.js:5:30)

```

**Comment by ignacionr** [comment]
This is very interesting! Since local versions don’t fail, we will need to investigate the test configuration; is it possible that it uses an expired token to run?

Sent from igPhone

On Oct 2, 2019, at 7:31 PM, Gene Hazan <notifications@github.com> wrote:

﻿

The test has failed:

nyc mocha "test/**/*.js" && eslint .

ajv-errors: Ajv option jsonPointers changed to true
/home/vsts/work/1/s/node_modules/@octokit/rest/lib/plugins/authentication/authenticate.js:25
        throw new Error('Token authentication requires a token to be set')
        ^

Error: Token authentication requires a token to be set
    at authenticate (/home/vsts/work/1/s/node_modules/@octokit/rest/lib/plugins/authentication/authenticate.js:25:15)
    at Object.getClient (/home/vsts/work/1/s/lib/github.js:3:280)
    at new GitHubCurationService (/home/vsts/work/1/s/providers/curation/github.js:7:469)
    at module.exports (/home/vsts/work/1/s/providers/curation/github.js:78:472)
    at Object.github [as service] (/home/vsts/work/1/s/providers/curation/githubConfig.js:3:708)
    at createApp (/home/vsts/work/1/s/app.js:3:2799)
    at Object.<anonymous> (/home/vsts/work/1/s/test/app.js:5:30)

**Comment by geneh** [comment]
It doesn't use any tokens. Could you please try running the local tests without env.json present?

**Comment by geneh** [comment]
I have verified this build definition is successful in the master branch but keeps on failing in this PR. Please correct the test.

**Comment by ignacionr** [comment]
Well you’re right, after all being a unit test it mustn’t rely on a properly configured environment (it’s not an integration test).
Will change it.

**Pull request merged**
