### PR TITLE
correct spelling error in environmental variable name

### PR DESCRIPTION
**Pull request by nellshamrell**
Before deploy, need to add the corrected environmental variable to dev-api and prod-api Azure app services.

Signed-off-by: Nell Shamrell <nells@microsoft.com>

### CODE REVIEW

**Review by jeffmendoza — APPROVED** [review]
Not sure what is going on with the build.

**Comment by nellshamrell** [comment]
That is a bit odd, I'm trying re-running it.

**Comment by nellshamrell** [comment]
Eh, still not working, I will take a look either next week or after the holidays. Not urgent by any means.

**Comment by nellshamrell** [comment]
Build is green now.

I've added "DEFINITION_MONGO_COLLECTION_NAME" to both the clearlydefined-api-dev and clearlydefined-api-prod configurations.

Merging, testing in the dev environment. If that works, I will merge to prod.

**Comment by nellshamrell** [comment]
This has been deployed and I have removed the mispelled env variable from both the clearly defined dev and prod environment and things seem to be working!

**Pull request merged**
