### PR TITLE
upgrades mkdirp and nyc to more secure versions

### PR DESCRIPTION
**Pull request by nellshamrell**
Replaces #719

Signed-off-by: Nell Shamrell <nells@microsoft.com>

### CODE REVIEW

**Comment by nellshamrell** [comment]
## Gathering information about the dependency

- [ ] Find the dependency on npm
- [ ] Find the source code repo for the dependency
- [ ] Look at the releases for the dependency
- [ ] See if there are any red flags in the release notes for the upgrade (and the releases between the current version and the version to update to)

## Gathering information about how the dependency is used in our application

- [ ] Trace how the dependency is used in the code (especially what API calls interact with it)
- [ ] Check if there is a test that covers the behavior

**Comment by nellshamrell** [comment]
# Basic Info

## mkdirp
* [npm page](https://www.npmjs.com/package/mkdirp)
* [github repo](https://github.com/isaacs/node-mkdirp)

## nyc
* [npm page](https://www.npmjs.com/package/nyc)
* [github repo](https://github.com/istanbuljs/nyc)

**Comment by nellshamrell** [comment]
nyc is a testing dependency and the tests are running fine locally, so I think the nyc change is good to merge.

Digging in a little more on mkdirp to make sure it's ok to merge.

**Comment by nellshamrell** [comment]
# Release notes for mkdirp

* Upgrading from 0.5.1 to 1.0.0
* release notes look pretty sparse, going to need to do some more manual checking https://github.com/isaacs/node-mkdirp/releases

**Comment by nellshamrell** [comment]
Looks like we use mkdirp here:

**service/providers/stores/fileDefinitionStore.js**
```javascript
(...)
const mkdirp = require('mkdirp')
(...)
  async store(coordinates, definition) {
    const filePath = this._toStoragePathFromCoordinates(coordinates) + '.json'
    const dirName = path.dirname(filePath)
    await promisify(mkdirp)(dirName)
    return promisify(fs.writeFile)(filePath, JSON.stringify(definition, null, 2), 'utf8')
  }
```

And looks like this is called here:
**service/providers/stores/fileConfig.js**
```javascript
function definition(options) {
  return require('./fileDefinitionStore')(options || { location: location + '-definition' })
}
```

Which is called from here:
**service/providers/index.js**
```javascript
module.exports = {
(...)
  definition: {
    azure: require('../providers/stores/azblobConfig').definition,
    file: require('../providers/stores/fileConfig').definition,
    mongo: require('../providers/stores/mongoConfig'),
    dispatch: require('../providers/stores/dispatchConfig')
  },
  attachment: {
    azure: require('../providers/stores/azblobConfig').attachment,
    file: require('../providers/stores/fileConfig').attachment
  },
(...)
    store: {
      azure: require('../providers/stores/azblobConfig').harvest,
      file: require('../providers/stores/fileConfig').harvest
    }
  }
}
```

Now to figure out how to test this...

**Comment by jeffmcaffer** [comment]
just stumbled on this...  For testing, are you happy assuming `mkdirp` is working as expected and just looking to ensure it's being called with the right args? If so, you can setup a test that overrides the file store's `require` using `proxyquire`. There are other tests in the repo that use this approach.

**Comment by nellshamrell** [comment]
Found a changelog for mkdirp https://github.com/isaacs/node-mkdirp/blob/master/CHANGELOG.md

Looks like the ^1.0.0 release is a full rewrite of the module.

I'm still working on testing it in our current code.

**Comment by nellshamrell** [comment]
I've broken the nyc update into it's own pull request in #783 

Because the mkdirp update is a breaking change and because this is a medium severity issue, rather than a high severity one, I'm going to delay updating mkdirp at least for the time being. To me it's not currently worth the risk of breaking our current code (if it is later upgraded to high severity, I am definitely willing to revisit it).

If anyone else has thoughts on this, feel free to re-open the PR for discussion.

**Pull request closed without merging**
